disabled_rules:
    - trailing_whitespace
    - private_over_fileprivate
opt_in_rules:
    - empty_count
    - empty_string
    - closure_end_indentation
    - closure_spacing
    - contains_over_first_not_nil
    - explicit_init
    - fatal_error_message
    - first_where
    - joined_default_parameter
    - literal_expression_end_indentation
    - overridden_super_call
    - prohibited_super_call
    - sorted_first_last
    - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment_on_call
    - yoda_condition
    - nslocalizedstring_key
    - unused_setter_value
excluded:
    - Carthage
    - Pods
    - SwiftLint/Common/3rdPartyLib
    - Deps
    - Scripts
line_length:
    warning: 200
    error: 250
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
type_name:
    min_length: 4
    max_length:
      warning: 40
      error: 50
    excluded:
      - pkgwant
      - pkgeflag
      - pkgstatus
      - pkgpriority
identifier_name:
    min_length:
      error: 3
    max_length:
      warning: 40
      error: 50
    excluded:
      - c
      - i
      - j
      - k
      - p
      - q
      - x
      - y
      - z
      - ok
      - to
      - id
large_tuple:
    warning: 4
    error: 5
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 750
    error: 1000
file_length:
    warning: 1200
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 50
    error: 60
reporter: "xcode"
