disabled_rules:
    - trailing_whitespace
opt_in_rules:
    - empty_count
    - empty_string
    - closure_end_indentation
    - closure_spacing
    - contains_over_first_not_nil
    - explicit_init
    - fatal_error_message
    - first_where
    - implicit_return
    - joined_default_parameter
    - literal_expression_end_indentation
    - overridden_super_call
    - prohibited_super_call
    - sorted_first_last
    - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment_on_call
    - yoda_condition
    - nslocalizedstring_key
    - unused_setter_value
excluded:
    - Carthage
    - Pods
    - SwiftLint/Common/3rdPartyLib
    - Deps
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
type_name:
    min_length: 4
    max_length:
      warning: 40
      error: 50
    excluded:
      - pkgwant
      - pkgeflag
      - pkgstatus
      - pkgpriority
identifier_name:
    min_length:
      error: 3
    max_length:
      warning: 40
      error: 50
    excluded:
      - c
      - i
      - j
      - k
      - p
      - q
      - x
      - y
      - z
      - ok
      - to
      - id
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 700
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 30
    error: 50
reporter: "xcode"
