#!/bin/sh

finish() {
	f="${1}"

	# No control fd: bail out
	[ -z "${f}" ] || [ -z "${SILEO}" ] && return

	read -r fd ver <<-EOF                    
			${SILEO}                                    
			EOF

	# Sileo control fd version < 1: bail out
	[ "${ver}" -ge 1 ] || return

	echo "finish:${f}" >&"${fd}"
}

finish uicache
exit 0
