#!/bin/sh

finish() {
	f="${1}"

	# No control fd: bail out
	[ -z "${f}" ] || [ -z "${SILEO}" ] && return

	read -r fd ver <<-EOF                    
			${SILEO}                                    
			EOF

	# Sileo control fd version < 1: bail out
	[ "${ver}" -ge 1 ] || return

	echo "finish:${f}" >&"${fd}"
}

case "$1" in
	remove|deconfigure)
		finish uicache
		;;

	upgrade|failed-upgrade)
		;;

	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 0
		;;
esac

exit 0
