#!/bin/sh

finish() {
        f="${1}"

        # No control fd: bail out
        [ -z "${f}" ] || [ -z "${SILEO}" ] && return

        # Sileo control fd version < 1: bail out
        [ "$(echo $SILEO | cut -d\  -f2)" -ge 1 ] || return

        echo "finish:${f}" >&$(echo $SILEO | cut -d\  -f1)
}

finish uicache
exit 0
